#Specifies how 1.8.x clients should see the cooldown indicator
#You can choose between TITLE, ACTION_BAR and DISABLED
#ONLY DISABLE IF YOU HAVE 1.9 COOLDOWN DISABLED ON YOUR SERVER
#1.8 PLAYERS MAY ASK WHY PVP IS NOT WORKING OTHERWISE
cooldown-indicator: 'TITLE'